"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require('dotenv').load({ silent: true });
const { NAME = 'feedbackfruits-knowledge-youtube-annotator', CAYLEY_ADDRESS = 'http://cayley:64210', KAFKA_ADDRESS = 'tcp://kafka:9092', INPUT_TOPIC = 'updates', OUTPUT_TOPIC = 'update_requests', YOUTUBE_API_KEY } = process.env;
exports.NAME = NAME;
exports.CAYLEY_ADDRESS = CAYLEY_ADDRESS;
exports.KAFKA_ADDRESS = KAFKA_ADDRESS;
exports.INPUT_TOPIC = INPUT_TOPIC;
exports.OUTPUT_TOPIC = OUTPUT_TOPIC;
exports.YOUTUBE_API_KEY = YOUTUBE_API_KEY;
