declare const NAME: string, CAYLEY_ADDRESS: string, KAFKA_ADDRESS: string, INPUT_TOPIC: string, OUTPUT_TOPIC: string, YOUTUBE_API_KEY: string;
declare const YT_REGEX: RegExp;
export { NAME, CAYLEY_ADDRESS, KAFKA_ADDRESS, INPUT_TOPIC, OUTPUT_TOPIC, YOUTUBE_API_KEY, YT_REGEX, };
